import { NextRequest, NextResponse } from "next/server";
import { verifySessionOwnership, safeLogger } from "@/lib/auth-helpers";
import { getOpenAIVoiceClient } from "@/lib/llm-provider";

/**
 * Creates an ephemeral OpenAI Realtime session token for WebRTC connection.
 * Permanent OPENAI_API_KEY is never exposed to the client browser.
 */
export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const { sessionId, instructions } = body;

    if (!sessionId) {
      return NextResponse.json({ error: "sessionId is required" }, { status: 400 });
    }

    const ownershipResult = await verifySessionOwnership(req, sessionId);
    if ("response" in ownershipResult) {
      return ownershipResult.response;
    }

    const { session } = ownershipResult;

    if (!process.env.OPENAI_API_KEY) {
      return NextResponse.json(
        {
          error:
            "OPENAI_API_KEY is not configured on the server. Realtime voice sessions require an OpenAI key.",
        },
        { status: 503 }
      );
    }

    const { realtimeModel } = getOpenAIVoiceClient();

    // Prepare questions plan generated by Nemotron
    const questions = (session.generated_questions || []) as Array<{
      question: string;
      focus: string;
    }>;

    const questionsPlan = questions.length > 0
      ? `\n\nINTERVIEW PLAN (Questions formulated by NVIDIA Nemotron):\n` +
        questions
          .map((q, idx) => `${idx + 1}. ${q.question} (Focus: ${q.focus})`)
          .join("\n")
      : "";

    const fullInstructions = `You are a professional behavioral interviewer conducting a real-time spoken interview.
Voice interaction is powered by OpenAI Realtime; question planning and post-interview evaluation are powered by NVIDIA Nemotron.

${instructions || ""}${questionsPlan}

Guidelines:
- Speak concisely and naturally in audio.
- Ask ONE question at a time from the plan.
- Briefly acknowledge candidate answers before moving forward.
- Do NOT give scores, grades, or coaching tips during the spoken call; evaluation will happen afterward.
- When all questions have been covered, say: "Thank you for your time. The interview is now complete."`;

    safeLogger.info("Requesting OpenAI Realtime ephemeral session token", {
      sessionId,
      model: realtimeModel,
    });

    // OpenAI GA Realtime API uses /v1/realtime/client_secrets
    const gaPayload = {
      session: {
        type: "realtime",
        model: realtimeModel,
        instructions: fullInstructions,
        audio: {
          input: {
            transcription: {
              model: "whisper-1",
            },
            turn_detection: {
              type: "server_vad",
              threshold: 0.5,
              prefix_padding_ms: 300,
              silence_duration_ms: 500,
            },
          },
          output: {
            voice: "alloy",
          },
        },
      },
    };

    let response = await fetch("https://api.openai.com/v1/realtime/client_secrets", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${process.env.OPENAI_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify(gaPayload),
    });

    // Fallback to legacy preview endpoint if client_secrets is unavailable
    if (response.status === 404) {
      safeLogger.warn("Falling back to legacy /v1/realtime/sessions");
      response = await fetch("https://api.openai.com/v1/realtime/sessions", {
        method: "POST",
        headers: {
          Authorization: `Bearer ${process.env.OPENAI_API_KEY}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          model: realtimeModel,
          voice: "alloy",
          modalities: ["audio", "text"],
          instructions: fullInstructions,
          input_audio_transcription: { model: "whisper-1" },
          turn_detection: {
            type: "server_vad",
            threshold: 0.5,
            prefix_padding_ms: 300,
            silence_duration_ms: 500,
          },
        }),
      });
    }

    if (!response.ok) {
      const errorText = await response.text();
      safeLogger.error("OpenAI Realtime session error", {
        status: response.status,
        body: errorText,
      });

      return NextResponse.json(
        {
          error: `Failed to create OpenAI Realtime session (${response.status}): ${errorText}`,
        },
        { status: response.status }
      );
    }

    const sessionData = await response.json();
    const ephemeralKey = sessionData.value || sessionData.client_secret?.value;

    return NextResponse.json({
      clientSecret: ephemeralKey,
      model: realtimeModel,
      expiresAt: sessionData.expires_at || sessionData.client_secret?.expires_at,
    });
  } catch (error: any) {
    safeLogger.error("Realtime session route failed", { error: error?.message });
    return NextResponse.json(
      { error: error?.message || "Failed to initialize realtime session" },
      { status: 500 }
    );
  }
}
